-- MySQL Script generated by MySQL Workbench
-- Mon Nov  8 09:43:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clase_30
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `clase_30` ;

-- -----------------------------------------------------
-- Schema clase_30
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clase_30` DEFAULT CHARACTER SET utf8 ;
USE `clase_30` ;

-- -----------------------------------------------------
-- Table `clase_30`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clase_30`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `clase_30`.`usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NOT NULL,
  `apellido` VARCHAR(40) NULL,
  `email` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(50) NULL,
  PRIMARY KEY (`id_usuarios`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clase_30`.`estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clase_30`.`estados` ;

CREATE TABLE IF NOT EXISTS `clase_30`.`estados` (
  `id_estados` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_estados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clase_30`.`notas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clase_30`.`notas` ;

CREATE TABLE IF NOT EXISTS `clase_30`.`notas` (
  `id_notas` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(200) NOT NULL,
  `descripcion` MEDIUMTEXT NOT NULL,
  `fecha_crea` DATETIME NOT NULL,
  `fecha_modi` DATETIME NULL,
  `elimina` BIT NOT NULL,
  `estados_id_estados` INT NOT NULL,
  `usuarios_id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_notas`, `estados_id_estados`),
  INDEX `fk_notas_estados_idx` (`estados_id_estados` ASC) VISIBLE,
  INDEX `fk_notas_usuarios1_idx` (`usuarios_id_usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_notas_estados`
    FOREIGN KEY (`estados_id_estados`)
    REFERENCES `clase_30`.`estados` (`id_estados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notas_usuarios1`
    FOREIGN KEY (`usuarios_id_usuarios`)
    REFERENCES `clase_30`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clase_30`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clase_30`.`categorias` ;

CREATE TABLE IF NOT EXISTS `clase_30`.`categorias` (
  `id_categorias` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(20) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`id_categorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clase_30`.`cat_nota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clase_30`.`cat_nota` ;

CREATE TABLE IF NOT EXISTS `clase_30`.`cat_nota` (
  `notas_id_notas` INT NOT NULL,
  `categorias_id_categorias` INT NOT NULL,
  PRIMARY KEY (`notas_id_notas`, `categorias_id_categorias`),
  INDEX `fk_cat_nota_categorias1_idx` (`categorias_id_categorias` ASC) VISIBLE,
  CONSTRAINT `fk_cat_nota_notas1`
    FOREIGN KEY (`notas_id_notas`)
    REFERENCES `clase_30`.`notas` (`id_notas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cat_nota_categorias1`
    FOREIGN KEY (`categorias_id_categorias`)
    REFERENCES `clase_30`.`categorias` (`id_categorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
